version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_nest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usuarios-bd
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - db_net

volumes:
  db_data:

networks:
  db_net:
    driver: bridge
